application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
hibernate:
  connection:
    characterEncoding: UTF-8
    CharSet: UTF-8
    useUnicode: true
  format_sql: true
  hbm2ddl:
    auto: update
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootmailsender022@gmail.com
    password: lvmnlyuvhqszsftu #SpringBootMailSender
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    protocol: smtp      
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/gp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  tomcat:
    uri-encoding: UTF-8

  error:
    include-message: always
  port: 443
   #ssl:
      #key-store: keystore.p12
      #key-store-password: GP2023-2024
      #keyStoreType: PKCS12
      #keyAlias: tomcat
